server:
  port: 8111

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walnut_cms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mail:
    host: smtp.qq.com
    port: 587
    username: your-email@qq.com
    password: your-smtp-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
        enabled: true
        location: D:/WorkSpace/walnut/walnut-cms-api/src/main/resources/upload/temp

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.walnut.cms.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 86400000  # 24小时
  refresh-expiration: 604800000  # 7天

# 验证码配置
kaptcha:
  border: "no"
  border.color: 105,179,90
  textproducer:
    font:
      color: black
      size: 30
      names: Arial,Courier
    char:
      length: 4
  image:
    width: 100
    height: 40

app:
  upload:
    dir: D:/WorkSpace/walnut/walnut-cms-api/src/main/resources/upload
    max-size: 104857600  # 100MB in bytes